#include <bits/stdc++.h>
using namespace std;


void solve() {
    int n;
    string s;
    cin >> n;
    cin >> s;

    // Ti = a for all odd i
    // Ti = b for all even i
    // S is generated by removing left or right characters from T

    // how can S be generated from T when n is even/odd
    // odd -> first letter must be a, first two letters can be "a", and allows for two adjacent letters
    // even -> first letter can be either but cannot have two of the same


    // notice that there are always 3 cases
    // 1. T left and right is a
    // 2. T left and right is b
    // 3. T left and right is (a, b) or (b, a)

    // case 1, 2 always goes to 3
    // depending on which side is taken case 3 goes to 1, 2

    // int a = 0;
    // int b = 0;
    // for (int i = 0; i < n; i++) {
    //     if (s[i] == 'a') {
    //         a++;
    //     }
    //     if (s[i] == 'b') {
    //         b++;
    //     }
    // }

    // states:
    // 0 -> both a
    // 1 -> both b
    // 2 -> different ends
    // 3 -> both are either a or b (but don't know)
    int state = (n & 1) ? 0 : 2;

    int a = 0;
    int b = 0;
    for (int i = 0; i < n; i++) {
        switch (state) {
        case 0:
            if (s[i] == 'b') {
                cout << "NO" << endl;
                return;
            }
            // s[i] = 'a';
            state = 2;
            break;

        case 1:
            if (s[i] == 'a') {
                cout << "NO" << endl;
                return;
            }
            // s[i] = 'b';
            state = 2;
            break;

        case 2:
            if (s[i] == 'a') {
                state = 1;

            } else if (s[i] == 'b') {
                state = 0;

            } else {
                state = 3;
            }
            break;

        case 3:
            if (s[i] != '?') {
                // we know what must go here
                state = (s[i] == 'a') ? 0 : 1;
                i--;

            } else {
                state = 2;
            }
            break;
            // easy if s[i] = a or b
            //
            // how to handle if s[i] = ?
            // it doesn't matter! since will always go back to state 2
        }
    }

    // what about balance of a, b?
    // hopefully our state machine just maintains it...
    cout << "YES" << endl;
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin >> t;
    while (t--) solve();
}
